name: MyLibTemplate.Api

services:
  mylibtemplate.api:
    image: ghcr.io/tiogars/dotnet-lib-template/dotnet-lib-template-api:latest
    build:
      context: .
      dockerfile: MyLibTemplate.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    # depends_on:
    #   - mylibtemplate.db

  # mylibtemplate.db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     SA_PASSWORD: "Your_password123"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlvolume:/var/opt/mssql