name: Build api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
        cache: true
        cache-dependency-path: MyLibTemplate.Api/MyLibTemplate.Api.csproj

    - run: dotnet restore --use-lock-file

    - run: dotnet build "MyLibTemplate.Api/MyLibTemplate.Api.csproj" --no-restore --configuration Release

    - run: dotnet test "MyLibTemplate.Api/MyLibTemplate.Api.csproj" --no-build --verbosity normal
