name: Build and test .NET

on:
  push:
    branches: [ "main" ]
    paths:
    - 'MyLibTemplate/**'
    - '!**.md'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'MyLibTemplate/**'
    - '!**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
        cache: true
    
    - run: dotnet restore --use-lock-file

    - run: dotnet build "MyLibTemplate/MyLibTemplate.csproj" --no-restore --configuration Release

    - run: dotnet test "MyLibTemplate/MyLibTemplate.csproj" --no-build --verbosity normal
