name: Release MyLibTemplate.Console

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true
        default: '1.0.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
        cache: true
        cache-dependency-path: MyLibTemplate.Console/MyLibTemplate.Console.csproj
    
    - run: dotnet restore --use-lock-file

    - run: dotnet build --no-restore --configuration Release

    - run: Compress-Archive -Path MyLibTemplate.Console/bin/Release/net8.0/* -DestinationPath MyLibTemplate.Console.zip

    - run: Compress-Archive -Path MyLibTemplate.Web/bin/Release/net8.0/* -DestinationPath MyLibTemplate.Web.zip

    - uses: actions/upload-artifact@v3
      with:
        name: MyLibTemplate.Console
        path: MyLibTemplate.Console.zip
