name: Release MyLibTemplate artefacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true
        default: '1.0.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
        cache: true
        cache-dependency-path: MyLibTemplate.Console/MyLibTemplate.Console.csproj
    
    - run: dotnet restore --use-lock-file

    - run: dotnet build --no-restore --configuration Release --runtime win-x64 --self-contained true

    - run: zip -r MyLibTemplate.Console.zip MyLibTemplate.Console/bin/Release/net8.0/

    - run: zip -r MyLibTemplate.Web.zip MyLibTemplate.Web/bin/Release/net8.0/

    - uses: actions/upload-artifact@v4
      with:
        name: MyLibTemplate.Console
        path: MyLibTemplate.Console.zip

    - uses: actions/upload-artifact@v4
      with:
        name: MyLibTemplate.Web
        path: MyLibTemplate.Web.zip