name: Release .NET

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      env:
        NUGET_USERNAME: tiogars
        NUGET_NAMESPACE: tiogars
      run: dotnet nuget add source --username ${{ env.NUGET_USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ env.NUGET_NAMESPACE }}/index.json"
    
    - name: Package
      run: dotnet pack --configuration Release

    - name: Push
      env:
        PROJECT_NAME: ${{ github.ref_name }}
        PROJECT_VERSION: ${{ github.event.release.tag_name }}
      run: dotnet nuget push "bin/Release/${{ env.PROJECT_NAME }}.${{ env.PROJECT_VERSION }}.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
