name: Release MyLibTemplate artefacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true
        default: '1.0.0'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
        cache: true
        cache-dependency-path: MyLibTemplate.Console/MyLibTemplate.Console.csproj
    
    - run: dotnet restore --use-lock-file

    - run: dotnet build --no-restore --configuration Release

    - run: dotnet publish MyLibTemplate.Console/MyLibTemplate.Console.csproj -c Release -r win-x64 --self-contained true -o publish/console

    - run: zip -r MyLibTemplate.Console.zip publish/console

    - run: gh release create ${{ inputs.version }} MyLibTemplate.Console.zip --title "Release ${{ inputs.version }}" --notes "${{ inputs.version }}"
