name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release'
        required: true
        default: '1.0.0'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
        cache: true
        cache-dependency-path: MyLibTemplate.Console/MyLibTemplate.Console.csproj
    
    - run: dotnet restore --use-lock-file

    - run: dotnet build --no-restore --configuration Release

    - run: dotnet publish MyLibTemplate.Console/MyLibTemplate.Console.csproj -c Release -r win-x64 --self-contained true
    - run: |
        cd ./MyLibTemplate.Console/bin/Release/net8.0/win-x64/publish
        zip -r ../../../../../../MyLibTemplate.Console-${{ inputs.version }}.zip .
        cd $GITHUB_WORKSPACE

    - run: dotnet publish MyLibTemplate.Web/MyLibTemplate.Web.csproj -c Release -r win-x64 --self-contained true
    - run: |
        cd ./MyLibTemplate.Web/bin/Release/net8.0/win-x64/publish
        zip -r ../../../../../../MyLibTemplate.Web-${{ inputs.version }}.zip .
        cd $GITHUB_WORKSPACE

    - run: gh release create ${{ inputs.version }} MyLibTemplate.Console-${{ inputs.version }}.zip MyLibTemplate.Web-${{ inputs.version }}.zip --title "Release ${{ inputs.version }}" --notes "${{ inputs.version }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
